apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    service: grafana
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      automountServiceAccountToken: true
      containers:
      - name: grafana
        image: vulhub/grafana:8.2.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000