---
apiVersion: v1
kind: Service
metadata:
  name: php-page-service
  labels:
    app: php-page
    service: php-page-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: php-page
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-page-deployment
  labels:
    app: php-page
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-page
      version: v1
  template:
    metadata:
      labels:
        app: php-page
        version: v1
    spec:
      serviceAccountName: default
      containers:
      - name: php-page-deployment
        image: alfesito/php-page:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---