apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"syringe","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"syringe"}},"template":{"metadata":{"labels":{"app":"syringe"}},"spec":{"automountServiceAccountToken":true,"containers":[{"image":"syringe:latest","imagePullPolicy":"IfNotPresent","name":"syringe","ports":[{"containerPort":3000}]}],"serviceAccount":"syringe","serviceAccountName":"syringe"}}}}
  # creationTimestamp: "2023-03-02T23:51:30Z"
  generation: 1
  name: syringe
  namespace: default
  resourceVersion: "829"
  uid: 6b84c5c7-e388-4c10-bffd-8e78869ef69b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: syringe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      # creationTimestamp: null
      labels:
        app: syringe
    spec:
      automountServiceAccountToken: true
      containers:
      - image: syringe:latest
        imagePullPolicy: IfNotPresent
        name: syringe
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: syringe
      serviceAccountName: syringe
      terminationGracePeriodSeconds: 30