apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "baseline" #privileged, baseline, restricted
      #enforce-version: "latest"
    exemptions:
      usernames: []
      runtimeClasses: []
      namespaces: []