kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: ObagH7lbO8LcyidX2bxh2Z9SD3EDuKshl+EEi2a6rV4=
      - identity: {}
